//get all
GET http://localhost:3001/api/persons

###
//get info
GET http://localhost:3001/info

###
//get single 
GET http://localhost:3001/api/persons/64116bfd2c0c4509f5b56bb5


###
//get single non existing
GET http://localhost:3001/api/persons/10000

###
//delete
DELETE http://localhost:3001/api/persons/6414c3cf447436d0f6a64f64


###
//post
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
      "name": "Testing post", 
      "number": "12345678"
    }

###
//post with content missing
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
      "name": "Testing post with content missing"
    }

###
//post with duplicate name
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
      "name": "dan abramov",
      "number": "1234567"
    }
